site_name: OPS233-Minecraft
site_url: https://squaremanran.github.io/OPS233-mc-pages/

repo_url: https://github.com/SquareManRan/OPS233-mc-pages
repo_name: SquareManRan/OPS233-mc-pages

nav:
  - home.md
  - Bedrock:
    - bedrock/windows10-mobile.md
    - bedrock/xbox.md
    - bedrock/switch.md
  - Features:
    - features/spawn.md
    - features/voicechat.md
    - features/armorstandeditor.md
    - features/autocrafting.md
    - features/deepslate-instamine.md

theme:
  name: material
  logo: assets/ops233gamingclub.png
  favicon: assets/ops233gamingclub.png
  features:
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  
edit_uri: edit/main/docs/
